name: Update Dash33 Documentation

on:
  push:
    branches: [ main ]
    paths:
      - 'src/**'
      - 'tests/**'
      - 'docs/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'src/**'
      - 'tests/**'
      - 'docs/**'

jobs:
  update-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable

      - name: Install cargo-doc
        run: cargo install cargo-doc

      - name: Install mermaid-cli
        run: npm install -g @mermaid-js/mermaid-cli

      - name: Generate API Documentation
        run: |
          cargo doc --no-deps --document-private-items
          cp -r target/doc docs/api

      - name: Update Architecture Diagrams
        run: |
          find docs -name "*.md" -type f -exec sh -c '
            for file do
              mmdc -i "$file" -o "${file%.md}.png"
            done
          ' sh {} +

      - name: Update Metrics Documentation
        run: |
          cargo run --bin update-metrics-docs

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          commit-message: "docs: Update dash33 documentation

          - Update API documentation
          - Regenerate architecture diagrams
          - Update metrics documentation

          Generated by GitHub Actions"
          title: "docs: Update dash33 documentation"
          body: |
            Automated documentation update for dash33:
            - Generated API documentation from code
            - Updated architecture diagrams
            - Updated metrics documentation
            
            Please review the changes and merge if appropriate.
          branch: docs-update-dash33
          base: main
